services:
  web:
    build:
      context: ./web/vendor/laravel/sail/runtimes/8.1
    extends:
      file: web/docker-compose.yml
      service: laravel.test
    depends_on:
      - mysql
      - redis
  mysql:
    extends:
      file: web/docker-compose.yml
      service: mysql
  redis:
    extends:
      file: web/docker-compose.yml
      service: redis
  memcached:
    extends:
      file: web/docker-compose.yml
      service: memcached
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181
    networks:
      - thought-stream
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - thought-stream

networks:
    thought-stream:
        name: thought-stream
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    sail-redis:
        driver: local
